### ISSUE TITLE
configure file is missing

### ISSUE THREAD

**Issue by mb-77** [lausser/check_logfiles#54]
I cannot find configure file in this repo

**Comment by lausser** [comment]
Which config file? There are thousands, but everybody creates his own.  Gesendet von meinem Windows 10-Gerät. Von:  <mailto:notifications@github.com> mb-77
 Gesendet:  Freitag, 31. Juli 2020 11:17
 An:  <mailto:check_logfiles@noreply.github.com> lausser/check_logfiles
 Cc:  <mailto:subscribed@noreply.github.com> Subscribed
 Betreff:  [lausser/check_logfiles] configure file is missing (#54)I cannot find configure file in this repo

-- 
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/lausser/check_logfiles/issues/54

**Comment by mb-77** [comment]
the configure file needed to compile the check_logfiles script 

point 1 README
1) Run the configure script to initialize variables and create a Makefile, etc.

**Comment by lausser** [comment]
There is a configure in the tar.gz which you find here. https://labs.consol.de/nagios/check_logfiles/index.html
This here is just my developer repo. If you checked it out, you have to run "autoreconf", then it will create the configure srcript.
