### ISSUE TITLE
second critical pattern doesn't worked

### ISSUE THREAD

**Issue by AgentZoy** [lausser/check_logfiles#55]
Hi
I want to use this check to check logfiles 
if it contains one of 2 critical patterns that mean show critical alert in nagios

First critical pattern is
MemoryException: xxx bytes not availableI need that check give critical if xxx more than n bytes
I know that xxx > 3.5 gb in bytes and in this case check must be In critical state
This is completed and worked

I want to add second critical pattern  TradeBase: not enough memory for index

And problem is that check ignore second critical pattern
I'm trying different variants but no one worked 

my config for check now is
searches = ({
  logfile => "test.log",
  criticalpatterns => {'MemoryException: (\d+) bytes not available',
                       'TradeBase: not enough memory for index(.*)'},
  options => "supersmartscript, capturegroups,noprotocol",
  script => sub {
    my $gigabytes = $ENV{CHECK_LOGFILES_CAPTURE_GROUP1} / (1024*1024*1024);
    if ($gigabytes > 3.5) {
      print $ENV{CHECK_LOGFILES_SERVICEOUTPUT};
      return 2;
    } else {
      return 0;
    }
  },
});

Script author replied

What you can try ist o use this as an example….
  criticalpatterns => {
    'door-open' => 'Door is open! (.*)',
    'door-closed' => 'Door is closed! (.*)' },
  options => 'script,capturegroups',
  script => sub {
    my $state = $CHECK_LOGFILES_PRIVATESTATE;
    my $date = $ENV{CHECK_LOGFILES_CAPTURE_GROUP1};
printf STDERR "%s\n", $ENV{CHECK_LOGFILES_KAKA};
    #... umrechnen in einen epoch-timestamp
   
    if ($ENV{CHECK_LOGFILES_PATTERN_KEY} eq 'door-closed') {
      delete $state->{opening_time};
      printf "Door %s is closed\n", $ENV{CHECK_LOGFILES_TAG};
      return 0;
    } elsif ($ENV{CHECK_LOGFILES_PATTERN_KEY} eq 'door-open') {
 
 
Criticalpatterns is written as key-value structure.
$ENV{CHECK_LOGFILES_PATTERN_KEY} is the key of the matching pattern
$ENV{CHECK_LOGFILES_CAPTURE_GROUP1} is the portion inside ()

I cant understand how to add second critical pattern (((

Can someone help?

**Comment by lausser** [comment]
```
criticalpatterns => {
   'door-open' => 'Door is open! (.)',
   'door-closed' => 'Door is closed! (.)' 
},
```
This is just an example. Here we see a hash with keys and values. Keys are identifiers which you later use as $ENV{CHECK_LOGFILES_PATTERN_KEY} in the supersmartscript. It tells you which of the patterns has matched. And the values of the criticalpatterns hash are the regular expressions.
Actually i do not understand why anybody would assume that this can work:
```
criticalpatterns => {'MemoryException: (\d+) bytes not available',
'TradeBase: not enough memory for index(.)'},
```


Ok, let me do your job, you can get a coffee in the meantime.
```
criticalpatterns => {
   'memory-exception' => 'MemoryException: (\d+) bytes not available',
   'tradebase' => 'TradeBase: not enough memory for index(.)',
},
...
script => sub {
  if ($ENV{CHECK_LOGFILES_PATTERN_KEY} eq 'memory-exception') {
    my $gigabytes = $ENV{CHECK_LOGFILES_CAPTURE_GROUP1} / (10241024*1024);
    if ($gigabytes > 3.5) {
      print $ENV{CHECK_LOGFILES_SERVICEOUTPUT};
      return 2;
    } else {
      return 0; 
    }
  } elsif ($ENV{CHECK_LOGFILES_PATTERN_KEY} eq 'tradebase') {
    # the second pattern matched. $ENV{CHECK_LOGFILES_CAPTURE_GROUP1} contains the index number
...
  }
},
```


The default way to define multiple criticalpatterns is
criticalpatterns => ['MemoryException: (\d+) bytes not available', 'TradeBase: not enough memory for index(.)'],
but as these two patterns, especially the capture group, are so different, you would need to execute a pattern match in the script again in order to find out which one has actually matched. The syntax with criticalpatterns as a hash helps you identify the matching one by putting the pattern identifier in $ENV{CHECK_LOGFILES_PATTERN_KEY}.

**Comment by AgentZoy** [comment]
searches = ({
  logfile => "test.log",
  criticalpatterns => {
   'memory-exception' => 'MemoryException: (\d+) bytes not available',
   'tradebase' => 'TradeBase: not enough memory for index',
},
#  okpatterns => { 'ok' => 'ok'},
  options => "supersmartscript,capturegroups,noprotocol",
script => sub {
  if ($ENV{CHECK_LOGFILES_PATTERN_KEY} eq 'memory-exception') {
    my $gigabytes = $ENV{CHECK_LOGFILES_CAPTURE_GROUP1} / (10241024*1024);
    if ($gigabytes > 3.5) {
      print $ENV{CHECK_LOGFILES_SERVICEOUTPUT};
      return 2;
    } else {
      return 0;
    }
  } elsif ($ENV{CHECK_LOGFILES_PATTERN_KEY} eq 'tradebase') {
    # the second pattern matched. $ENV{CHECK_LOGFILES_CAPTURE_GROUP1} contains the index number
    return 2;
  }
},
}

Where is mistake? I understand that i don't know Perl thats why I have stupid questions and mistakes (((

AND BIG THANKS FOR YOUR HELP

**Comment by AgentZoy** [comment]
BIG THANKS TO YOU
Now can't understand why memory except check no working  ((((
 elseif condition works

@searches = ({
  logfile => "test.log",
  criticalpatterns => {
   'memory-exception' => 'MemoryException: (\d+) bytes not available',
   'tradebase' => 'TradeBase: not enough memory for index',
},
#  okpatterns => { 'ok' => 'ok'},
  options => "supersmartscript,capturegroups,noprotocol",
script => sub {

if ($ENV{CHECK_LOGFILES_PATTERN_KEY} eq 'memory-exception') {
    my $gigabytes = $ENV{CHECK_LOGFILES_CAPTURE_GROUP1} / (10241024*1024);
    if ($gigabytes > 3.5) {
      print $ENV{CHECK_LOGFILES_SERVICEOUTPUT};
      return 2;
    } else {
      return 0;
    }
  } elsif ($ENV{CHECK_LOGFILES_PATTERN_KEY} eq 'tradebase') {
    # the second pattern matched. $ENV{CHECK_LOGFILES_CAPTURE_GROUP1} contains the index number
    return 1;
  }
},

});

**Comment by AgentZoy** [comment]
THANKS YOU FOR YOUR TIME AND HELP

**Comment by AgentZoy** [comment]
Can you help How i can implement that check stays in critical until for example ok word is founded in log file
Now check works in this way
If in check moment it found critical pattern it's show critical
Nothing added to test log file
Net check run
State OK
I will try by myself but not sure that i will success

**Comment by lausser** [comment]
You have to look for the “sticky option” and set

Okpatterns => [“the ok pattern”]



Von: AgentZoy [mailto:notifications@github.com]
Gesendet: Donnerstag, 6. August 2020 14:12
An: lausser/check_logfiles <check_logfiles@noreply.github.com>
Cc: Gerhard Lausser <Gerhard.Lausser@consol.de>; State change 
<state_change@noreply.github.com>
Betreff: Re: [lausser/check_logfiles] second critical pattern doesn't worked 
(#55)



Can you help How i can implement that check stays in critical until for 
example ok word is founded in log file
Now check works in this way
If in check moment it found critical pattern it's show critical
Nothing added to test log file
Net check run
State OK
I will try by myself but not sure that i will success

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub 
<https://github.com/lausser/check_logfiles/issues/55#issuecomment-669889846> 
, or unsubscribe

**Comment by AgentZoy** [comment]
Aha I understand logic
Thanks

**Comment by AgentZoy** [comment]
He goes to ok state after second check
In log files are critical records
1st run result critical
2nd run result ok But no ok pattern exist in file Also it's ignore memory in bytes record
Why ?
config file now
 okpatterns => ['ok'],
 logfile conetnt
@searches = ({
  logfile => "test.log",
  criticalpatterns => {
   'memory-exception' => 'MemoryException: (\d+) bytes not available',
   'tradebase' => 'TradeBase: not enough memory for index',
},
   okpatterns => ['ok'],
  options => "supersmartscript,capturegroups,noprotocol",
script => sub {

if ($ENV{CHECK_LOGFILES_PATTERN_KEY} eq 'memory-exception') {
    my $gigabytes = $ENV{CHECK_LOGFILES_CAPTURE_GROUP1} / (1024*1024*1024);
    if ($gigabytes > 3.5) {
      print $ENV{CHECK_LOGFILES_SERVICEOUTPUT};
      return 2;
    } else {
      return 0;
    }
  } elsif ($ENV{CHECK_LOGFILES_PATTERN_KEY} eq 'tradebase') {
    # the second pattern matched. $ENV{CHECK_LOGFILES_CAPTURE_GROUP1} contains the index number
    return 2;
  }
},

});

**Comment by AgentZoy** [comment]
Last that I want you help me
I want to take last logfile in log folder
I tested in this way before
./check_logfiles --logfile 'ls -tr | tail -1' --criticalpattern 'TradeBase: not enough memory for index'
It works
But how to execute it in config file
I tried in perl style but no one variant works

@searches = ({
  logfile => qx/ls -tr | tail -1/,
